package metier;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 15 juin 2015 09:19:44 by Hibernate Tools 4.3.1

/**
 * Inscrit generated by hbm2java
 */
@Entity
@Table(name = "inscrit", catalog = "permispiste")
public class Inscrit implements java.io.Serializable {

	private InscritId id;
	private Apprenant apprenant;
	private Calendrier calendrier;
	private Jeu jeu;

	public Inscrit() {
	}

	public Inscrit(InscritId id, Apprenant apprenant, Calendrier calendrier,
			Jeu jeu) {
		this.id = id;
		this.apprenant = apprenant;
		this.calendrier = calendrier;
		this.jeu = jeu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numapprenant", column = @Column(name = "NUMAPPRENANT", nullable = false)),
			@AttributeOverride(name = "datejour", column = @Column(name = "DATEJOUR", nullable = false, length = 10)),
			@AttributeOverride(name = "numjeu", column = @Column(name = "NUMJEU", nullable = false)) })
	public InscritId getId() {
		return this.id;
	}

	public void setId(InscritId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMAPPRENANT", nullable = false, insertable = false, updatable = false)
	public Apprenant getApprenant() {
		return this.apprenant;
	}

	public void setApprenant(Apprenant apprenant) {
		this.apprenant = apprenant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DATEJOUR", nullable = false, insertable = false, updatable = false)
	public Calendrier getCalendrier() {
		return this.calendrier;
	}

	public void setCalendrier(Calendrier calendrier) {
		this.calendrier = calendrier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMJEU", nullable = false, insertable = false, updatable = false)
	public Jeu getJeu() {
		return this.jeu;
	}

	public void setJeu(Jeu jeu) {
		this.jeu = jeu;
	}

}
